services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  KonradMichalik\Typo3EnvironmentIndicator\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  KonradMichalik\Typo3EnvironmentIndicator\TypoScript\TechnicalContextConditionFunctionsProvider:
    public: true

  KonradMichalik\Typo3EnvironmentIndicator\Backend\ToolbarItems\ContextItem:
    public: true
