services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  KonradMichalik\Typo3EnvironmentIndicator\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  KonradMichalik\Typo3EnvironmentIndicator\TypoScript\TechnicalContextConditionFunctionsProvider:
    public: true

  KonradMichalik\Typo3EnvironmentIndicator\Backend\ToolbarItems\ContextItem:
    public: true

  KonradMichalik\Typo3EnvironmentIndicator\Backend\ToolbarItems\TopbarItem:
    public: true

  dashboard.widget.EnvironmentIndicator:
    class: 'KonradMichalik\Typo3EnvironmentIndicator\Widgets\EnvironmentIndicatorWidget'
    tags:
      - name: dashboard.widget
        identifier: 'environmentIndicator'
        groupNames: 'systemInfo'
        title: 'LLL:EXT:typo3_environment_indicator/Resources/Private/Language/locallang.xlf:widgets.environmentIndicator.title'
        description: 'LLL:EXT:typo3_environment_indicator/Resources/Private/Language/locallang.xlf:widgets.environmentIndicator.description'
        iconIdentifier: 'actions-globe-alt'
        height: 'small'
        width: 'small'
